name: Upload instagram reel
on:
  workflow_dispatch:
    inputs:
      source:
        type: string
        description: source instagram account

  push:
    branches: [main]

env: 
  SOURCE_ACCOUNT: soooors
jobs:
  print_input:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: | 
          echo "${{ inputs.source }}"

      - name: Print secret
        run: |
          echo "${{ secrets.INSTAGRAM_TOKEN }}"

      - name: Print vars
        run: |
          echo "${{ vars.SOURCE }}"
      - name: Print env
        run: |
          echo "$SOURCE_ACCOUNT"
         
  

      
      