name: Upload instagram reel
on:
  workflow_dispatch:
    inputs:
      source:
        type: string
        description: source instagram account
jobs:
  print_input:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: | 
          echo "${{ inputs.source }}"

      - name: Print secret
        run: |
          echo "${{ secrets.INSTAGRAM_TOKEN }}"

      - name: Print vars
        run: |
          echo "${{ vars.SOURCE }}"

  

      
      