name: Upload instagram reel
on:
  workflow_dispatch:
    inputs:
      source:
        type: string
        description: source instagram account
jobs:
  print_input:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: | 
          echo "${{ inputs.source }}"

      - name: Print secret
        run: |
          echo "${{ secrets.instagram_token }}"

      - name: Print env
        run: |
          echo "${{ env.source }}"

  

      
      